# Generated by Django 5.2.6 on 2025-09-12 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.IntegerField(choices=[(1, 'HOURLY'), (2, 'MONTHLY')], default=1)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.CharField(max_length=128)),
                ('details', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance_type', models.IntegerField(choices=[(1, 'TIME IN'), (2, 'TIME OUT')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('allowance_type', models.IntegerField(choices=[(1, 'MEAL ALLOWANCE'), (2, 'TRANSPORTATION ALLOWANCE'), (3, 'MEDICAL ALLOWANCE'), (4, 'BONUS')])),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.IntegerField(choices=[(1, 'SICK'), (2, 'MATERNITY'), (3, 'LEAVE WITHOUT PAY')])),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_days', models.IntegerField(default=0)),
                ('days_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Generated'), (3, 'Approved'), (4, 'Paid'), (5, 'Cancelled')], default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.employee')),
            ],
            options={
                'ordering': ['employee__user__last_name'],
                'unique_together': {('employee', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='PayslipAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.IntegerField(choices=[(1, 'MEAL ALLOWANCE'), (2, 'TRANSPORTATION ALLOWANCE'), (3, 'MEDICAL ALLOWANCE'), (4, 'BONUS')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_allowances', to='payroll.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.IntegerField(choices=[(1, 'TAX DEDUCTION'), (2, 'HEALTH INSURANCE'), (3, 'SOCIAL SECURITY'), (4, 'OTHERS')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_deductions', to='payroll.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_type', models.IntegerField(choices=[(1, 'TAX DEDUCTION'), (2, 'HEALTH INSURANCE'), (3, 'SOCIAL SECURITY'), (4, 'OTHERS')])),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
    ]
