# Generated by Django 5.2.6 on 2025-09-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='allowance_type',
            field=models.IntegerField(choices=[(0, 'MEAL ALLOWANCE'), (1, 'TRANSPORTATION ALLOWANCE'), (2, 'MEDICAL ALLOWANCE'), (3, 'BONUS')]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.IntegerField(choices=[(0, 'PAID_LEAVE'), (1, 'SICK'), (2, 'MATERNITY'), (3, 'LEAVE WITHOUT PAY'), (4, 'HALF DAY LEAVE')]),
        ),
        migrations.AlterField(
            model_name='payslipallowance',
            name='allowance_type',
            field=models.IntegerField(choices=[(0, 'MEAL ALLOWANCE'), (1, 'TRANSPORTATION ALLOWANCE'), (2, 'MEDICAL ALLOWANCE'), (3, 'BONUS')]),
        ),
        migrations.AlterField(
            model_name='payslipdeduction',
            name='deduction_type',
            field=models.IntegerField(choices=[(0, 'LOAN'), (1, 'HEALTH INSURANCE'), (2, 'SOCIAL SECURITY'), (3, 'OTHERS')]),
        ),
        migrations.AlterField(
            model_name='salarydeduction',
            name='deduction_type',
            field=models.IntegerField(choices=[(0, 'LOAN'), (1, 'HEALTH INSURANCE'), (2, 'SOCIAL SECURITY'), (3, 'OTHERS')]),
        ),
    ]
