# Generated by Django 5.2.6 on 2025-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_alter_allowance_allowance_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="pay_frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Biweekly"),
                    ("semi_monthly", "Semi Monthly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="withholding_tax",
            field=models.DecimalField(decimal_places=2, max_digits=10, blank=True, null=True),
        ),
    ]
