# Generated by Django 5.2.6 on 2025-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
