# Generated by Django 5.2.6 on 2025-09-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='embedded_picture_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
